// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuotationAPI.Data;

#nullable disable

namespace QuotationAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240117165015_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuotationAPI.Models.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("YearOfMake")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId")
                        .IsUnique();

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("58e2bab6-a2b2-4e59-835d-6685e7db659a"),
                            Make = "Ford",
                            QuotationId = new Guid("68705687-2332-4b63-a98f-7b36cd538a22"),
                            YearOfMake = 2020
                        },
                        new
                        {
                            Id = new Guid("2ce1d87b-3db1-487a-8fe8-77cc1269bdcb"),
                            Make = "Mercedes",
                            QuotationId = new Guid("76474e11-26b2-4fe4-a945-409fdf8d5569"),
                            YearOfMake = 2016
                        },
                        new
                        {
                            Id = new Guid("11fcae53-b1a5-4615-8465-0771ff068ab9"),
                            Make = "BMW",
                            QuotationId = new Guid("54f0c926-0981-4898-8f99-6031670692e4"),
                            YearOfMake = 2012
                        },
                        new
                        {
                            Id = new Guid("821a68df-338d-4831-9ae8-a4b141d684c7"),
                            Make = "Audi",
                            QuotationId = new Guid("917c3001-5d56-4500-807b-8f80971200e9"),
                            YearOfMake = 2013
                        },
                        new
                        {
                            Id = new Guid("65ae53c6-59db-47a8-a5d8-89968b479a5b"),
                            Make = "Dodge",
                            QuotationId = new Guid("dfb4a00e-0fd6-4887-9d11-4ad63ca02542"),
                            YearOfMake = 2020
                        },
                        new
                        {
                            Id = new Guid("f4435f6d-4d8b-4b15-9180-18161da22fcf"),
                            Make = "Porsche",
                            QuotationId = new Guid("1f90fa97-6894-4343-a83a-200682cbcb12"),
                            YearOfMake = 2013
                        },
                        new
                        {
                            Id = new Guid("4219ed35-e311-41e6-bfe6-1097de9252fe"),
                            Make = "BMW",
                            QuotationId = new Guid("ffeba65a-c549-4e9a-ae66-56e336181f66"),
                            YearOfMake = 2016
                        },
                        new
                        {
                            Id = new Guid("47566373-6e02-412c-814e-97e356d3c7c4"),
                            Make = "Mercedes",
                            QuotationId = new Guid("771937e2-a726-42e6-b36a-6b82587333a3"),
                            YearOfMake = 2008
                        },
                        new
                        {
                            Id = new Guid("edd60d96-0705-4236-a530-f55e4257f24e"),
                            Make = "Audi",
                            QuotationId = new Guid("b152185e-2758-4869-bf5a-7b8e7c4cebca"),
                            YearOfMake = 2009
                        },
                        new
                        {
                            Id = new Guid("f79415ff-bc8a-4918-903d-8dfcb725258e"),
                            Make = "Kia",
                            QuotationId = new Guid("f3cd659f-8fc0-4a2d-ad34-82e5c42ece93"),
                            YearOfMake = 2011
                        },
                        new
                        {
                            Id = new Guid("20e3b7f4-a797-47b5-912e-a16403833c29"),
                            Make = "Kia",
                            QuotationId = new Guid("eed6f41b-6b49-4f3f-98e6-338c0a5d3e80"),
                            YearOfMake = 2013
                        },
                        new
                        {
                            Id = new Guid("a67468cb-b782-4278-851c-89226973025a"),
                            Make = "Dodge",
                            QuotationId = new Guid("503113ca-d149-4a23-87ee-9383f0906a1a"),
                            YearOfMake = 2019
                        },
                        new
                        {
                            Id = new Guid("17f31492-a544-476a-8e94-70a9186bbbe5"),
                            Make = "Hyundai",
                            QuotationId = new Guid("54a09153-a864-47b6-aad1-1436bd3a82e9"),
                            YearOfMake = 2018
                        },
                        new
                        {
                            Id = new Guid("00d60f20-d994-4551-95c6-eba328cfd548"),
                            Make = "Hyundai",
                            QuotationId = new Guid("4f2191fb-ac74-48b7-ab36-7b9164f029e5"),
                            YearOfMake = 2022
                        },
                        new
                        {
                            Id = new Guid("d05e22dd-67e0-49e0-ad87-a1878554a1a0"),
                            Make = "Ford",
                            QuotationId = new Guid("d86cff03-1995-46b2-b343-1c44973938e2"),
                            YearOfMake = 2023
                        },
                        new
                        {
                            Id = new Guid("41cf071b-3588-4a85-9eb5-f3cfc5e42a1e"),
                            Make = "Kia",
                            QuotationId = new Guid("dcad5558-5c15-4fa0-b599-9f0f9e132e40"),
                            YearOfMake = 2023
                        },
                        new
                        {
                            Id = new Guid("276efad2-ce90-4e26-b902-6485707958d9"),
                            Make = "BMW",
                            QuotationId = new Guid("ac0fd75e-f0ed-4648-afb6-fb696ed4e470"),
                            YearOfMake = 2010
                        },
                        new
                        {
                            Id = new Guid("d6e11d03-56e0-441e-8464-9de1b6aa14f1"),
                            Make = "Chevrolet",
                            QuotationId = new Guid("a5bfa199-a4f3-4c85-af9c-5a257d8c76fc"),
                            YearOfMake = 2022
                        },
                        new
                        {
                            Id = new Guid("7c96acba-6221-4dcb-a9d2-523938e30f00"),
                            Make = "Porsche",
                            QuotationId = new Guid("084564b7-f2f5-4b94-8060-10b878c4cadf"),
                            YearOfMake = 2024
                        },
                        new
                        {
                            Id = new Guid("0c012b55-8cbb-4fc1-8261-d652e839e766"),
                            Make = "Honda",
                            QuotationId = new Guid("2f29a06d-1ee9-4f89-98b3-6a5670286855"),
                            YearOfMake = 2023
                        });
                });

            modelBuilder.Entity("QuotationAPI.Models.PolicyOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PolicyOwners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3935a636-2e24-4c97-974a-885f26e3378b"),
                            FirstName = "William",
                            LastName = "Shakespeare"
                        },
                        new
                        {
                            Id = new Guid("255ea053-4c40-4dc2-80b0-1871b53385bb"),
                            FirstName = "Georges",
                            LastName = "White"
                        },
                        new
                        {
                            Id = new Guid("6636bf22-5903-4042-9311-c07aba1eafbe"),
                            FirstName = "Amelia",
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = new Guid("e836e35b-1497-4354-87e8-975f3d1da676"),
                            FirstName = "Liam",
                            LastName = "Parker"
                        },
                        new
                        {
                            Id = new Guid("9fa70264-11ef-4bad-8ef5-e134f149a190"),
                            FirstName = "Eleanor",
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = new Guid("6968dcc3-a7ee-4df4-8cbd-b005c3afc7ae"),
                            FirstName = "Alexander",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = new Guid("22652cf1-83e0-4f60-ae98-f0e108ccc332"),
                            FirstName = "Olivia",
                            LastName = "Garcia"
                        },
                        new
                        {
                            Id = new Guid("ef264c54-1310-440a-9f43-ee550d8d3a6d"),
                            FirstName = "Noah",
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = new Guid("6b00a876-56ec-47b7-9c4d-cbc491438560"),
                            FirstName = "Maya",
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = new Guid("17a7be3b-77ad-45d8-9e57-efc86d3fdacd"),
                            FirstName = "Ethan",
                            LastName = "Anderson"
                        });
                });

            modelBuilder.Entity("QuotationAPI.Models.Quotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PolicyOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuotationStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolicyOwnerId");

                    b.ToTable("Quotations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("68705687-2332-4b63-a98f-7b36cd538a22"),
                            CreationDate = new DateTime(2024, 1, 17, 18, 50, 15, 417, DateTimeKind.Local).AddTicks(6192),
                            PolicyOwnerId = new Guid("3935a636-2e24-4c97-974a-885f26e3378b"),
                            QuotationStatus = 1
                        },
                        new
                        {
                            Id = new Guid("76474e11-26b2-4fe4-a945-409fdf8d5569"),
                            CreationDate = new DateTime(2024, 1, 17, 18, 50, 15, 417, DateTimeKind.Local).AddTicks(6254),
                            PolicyOwnerId = new Guid("255ea053-4c40-4dc2-80b0-1871b53385bb"),
                            QuotationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("54f0c926-0981-4898-8f99-6031670692e4"),
                            CreationDate = new DateTime(2024, 1, 17, 18, 50, 15, 417, DateTimeKind.Local).AddTicks(6257),
                            PolicyOwnerId = new Guid("e836e35b-1497-4354-87e8-975f3d1da676"),
                            QuotationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("917c3001-5d56-4500-807b-8f80971200e9"),
                            CreationDate = new DateTime(2024, 1, 17, 18, 50, 15, 417, DateTimeKind.Local).AddTicks(6260),
                            PolicyOwnerId = new Guid("6636bf22-5903-4042-9311-c07aba1eafbe"),
                            QuotationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("dfb4a00e-0fd6-4887-9d11-4ad63ca02542"),
                            CreationDate = new DateTime(2024, 1, 17, 18, 50, 15, 417, DateTimeKind.Local).AddTicks(6262),
                            PolicyOwnerId = new Guid("6968dcc3-a7ee-4df4-8cbd-b005c3afc7ae"),
                            QuotationStatus = 1
                        },
                        new
                        {
                            Id = new Guid("1f90fa97-6894-4343-a83a-200682cbcb12"),
                            CreationDate = new DateTime(2024, 1, 17, 18, 50, 15, 417, DateTimeKind.Local).AddTicks(6264),
                            PolicyOwnerId = new Guid("9fa70264-11ef-4bad-8ef5-e134f149a190"),
                            QuotationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("ffeba65a-c549-4e9a-ae66-56e336181f66"),
                            CreationDate = new DateTime(2024, 1, 17, 18, 50, 15, 417, DateTimeKind.Local).AddTicks(6266),
                            PolicyOwnerId = new Guid("ef264c54-1310-440a-9f43-ee550d8d3a6d"),
                            QuotationStatus = 1
                        },
                        new
                        {
                            Id = new Guid("771937e2-a726-42e6-b36a-6b82587333a3"),
                            CreationDate = new DateTime(2024, 1, 17, 18, 50, 15, 417, DateTimeKind.Local).AddTicks(6268),
                            PolicyOwnerId = new Guid("6b00a876-56ec-47b7-9c4d-cbc491438560"),
                            QuotationStatus = 1
                        },
                        new
                        {
                            Id = new Guid("b152185e-2758-4869-bf5a-7b8e7c4cebca"),
                            CreationDate = new DateTime(2024, 1, 17, 18, 50, 15, 417, DateTimeKind.Local).AddTicks(6270),
                            PolicyOwnerId = new Guid("9fa70264-11ef-4bad-8ef5-e134f149a190"),
                            QuotationStatus = 1
                        },
                        new
                        {
                            Id = new Guid("f3cd659f-8fc0-4a2d-ad34-82e5c42ece93"),
                            CreationDate = new DateTime(2024, 1, 17, 18, 50, 15, 417, DateTimeKind.Local).AddTicks(6272),
                            PolicyOwnerId = new Guid("e836e35b-1497-4354-87e8-975f3d1da676"),
                            QuotationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("eed6f41b-6b49-4f3f-98e6-338c0a5d3e80"),
                            CreationDate = new DateTime(2024, 1, 17, 18, 50, 15, 417, DateTimeKind.Local).AddTicks(6274),
                            PolicyOwnerId = new Guid("6b00a876-56ec-47b7-9c4d-cbc491438560"),
                            QuotationStatus = 1
                        },
                        new
                        {
                            Id = new Guid("503113ca-d149-4a23-87ee-9383f0906a1a"),
                            CreationDate = new DateTime(2024, 1, 17, 18, 50, 15, 417, DateTimeKind.Local).AddTicks(6276),
                            PolicyOwnerId = new Guid("17a7be3b-77ad-45d8-9e57-efc86d3fdacd"),
                            QuotationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("54a09153-a864-47b6-aad1-1436bd3a82e9"),
                            CreationDate = new DateTime(2024, 1, 17, 18, 50, 15, 417, DateTimeKind.Local).AddTicks(6278),
                            PolicyOwnerId = new Guid("ef264c54-1310-440a-9f43-ee550d8d3a6d"),
                            QuotationStatus = 1
                        },
                        new
                        {
                            Id = new Guid("4f2191fb-ac74-48b7-ab36-7b9164f029e5"),
                            CreationDate = new DateTime(2024, 1, 17, 18, 50, 15, 417, DateTimeKind.Local).AddTicks(6280),
                            PolicyOwnerId = new Guid("9fa70264-11ef-4bad-8ef5-e134f149a190"),
                            QuotationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("d86cff03-1995-46b2-b343-1c44973938e2"),
                            CreationDate = new DateTime(2024, 1, 17, 18, 50, 15, 417, DateTimeKind.Local).AddTicks(6282),
                            PolicyOwnerId = new Guid("e836e35b-1497-4354-87e8-975f3d1da676"),
                            QuotationStatus = 1
                        },
                        new
                        {
                            Id = new Guid("dcad5558-5c15-4fa0-b599-9f0f9e132e40"),
                            CreationDate = new DateTime(2024, 1, 17, 18, 50, 15, 417, DateTimeKind.Local).AddTicks(6284),
                            PolicyOwnerId = new Guid("6636bf22-5903-4042-9311-c07aba1eafbe"),
                            QuotationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("ac0fd75e-f0ed-4648-afb6-fb696ed4e470"),
                            CreationDate = new DateTime(2024, 1, 17, 18, 50, 15, 417, DateTimeKind.Local).AddTicks(6286),
                            PolicyOwnerId = new Guid("3935a636-2e24-4c97-974a-885f26e3378b"),
                            QuotationStatus = 1
                        },
                        new
                        {
                            Id = new Guid("a5bfa199-a4f3-4c85-af9c-5a257d8c76fc"),
                            CreationDate = new DateTime(2024, 1, 17, 18, 50, 15, 417, DateTimeKind.Local).AddTicks(6288),
                            PolicyOwnerId = new Guid("22652cf1-83e0-4f60-ae98-f0e108ccc332"),
                            QuotationStatus = 1
                        },
                        new
                        {
                            Id = new Guid("084564b7-f2f5-4b94-8060-10b878c4cadf"),
                            CreationDate = new DateTime(2024, 1, 17, 18, 50, 15, 417, DateTimeKind.Local).AddTicks(6290),
                            PolicyOwnerId = new Guid("6636bf22-5903-4042-9311-c07aba1eafbe"),
                            QuotationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("2f29a06d-1ee9-4f89-98b3-6a5670286855"),
                            CreationDate = new DateTime(2024, 1, 17, 18, 50, 15, 417, DateTimeKind.Local).AddTicks(6292),
                            PolicyOwnerId = new Guid("22652cf1-83e0-4f60-ae98-f0e108ccc332"),
                            QuotationStatus = 0
                        });
                });

            modelBuilder.Entity("QuotationAPI.Models.Car", b =>
                {
                    b.HasOne("QuotationAPI.Models.Quotation", "Quotation")
                        .WithOne("Car")
                        .HasForeignKey("QuotationAPI.Models.Car", "QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("QuotationAPI.Models.Quotation", b =>
                {
                    b.HasOne("QuotationAPI.Models.PolicyOwner", "PolicyOwner")
                        .WithMany("Quotations")
                        .HasForeignKey("PolicyOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolicyOwner");
                });

            modelBuilder.Entity("QuotationAPI.Models.PolicyOwner", b =>
                {
                    b.Navigation("Quotations");
                });

            modelBuilder.Entity("QuotationAPI.Models.Quotation", b =>
                {
                    b.Navigation("Car")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
